spring:
    application:
      name: share

server:
  servlet:
    context-path: /share

data:
  storage:
    path: C:\Users\Vishnu Kant Gupta\Documents\nse_data
rest:
  cache:
    path: ${data.storage.path}\cache
    enable: true
